name: bar-sync

on:
  push:
    paths:
      - bar/*
      - .github/workflows/bar-sync.yml
  pull_request:
    paths:
      - bar/*
      - .github/workflows/bar-sync.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Test
        run: |
          TEST="|qsmxt|"
          echo "TEST=$TEST" >> $GITHUB_ENV
      - run: echo "TEST=env.TEST"
      - name: Run a multi-line script
        if: contains('|fsl|mrtrix3|devbase|qsmxt|mrtrix3tissue|samri|', env.TEST)
        run: |
          git config --local user.name "Github Action"
          git config --local user.email "actions@github.com"
          git config pull.ff only
          git subtree push --prefix bar https://github-actions:${{secrets.BAR_SYNC}}@github.com/aswinnarayanan/bar.git main
