name: bar-sync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Run a multi-line script
        run: |
          git config --local user.name "Github Action"
          git config --local user.email "actions@github.com"
          git config pull.ff only
          git remote add subtree https://github-actions:${{secrets.BAR_SYNC}}@github.com/aswinnarayanan/bar.git
          git subtree push --prefix bar subtree main
