name: Foo-Bar Action Initiator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  foo-bar:
    runs-on: ubuntu-latest
    steps:
      - name: FOO - Dispatch initiating repository event
        run: |
          curl -X POST https://api.github.com/repos/aswinnarayanan/bar/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "foo", "client_payload": { "GITHUB_REPOSITORY": "'"$GITHUB_REPOSITORY"'", "GITHUB_REPOSITORY_NAME": "'"${{ github.event.repository.name }}"'", "GITHUB_SHA": "'"$GITHUB_SHA"'" }}'
